---
- hosts: all

  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker
        state: latest
      become: true

    - name: Build container image locally
      community.docker.docker_image:
        name: wh-starstone
        source: build
        state: present
        build:
          path: ..
          platform: linux/amd64
        force_source: true
      delegate_to: 127.0.0.1

    - name: Export container image locally
      community.docker.docker_image:
        name: wh-starstone
        archive_path: /tmp/wh-starstone-img.tar
        source: local
      delegate_to: 127.0.0.1

    - name: Upload image to server
      ansible.builtin.copy:
        src: /tmp/wh-starstone-img.tar
        dest: /tmp/wh-starstone-img.tar

    - name: Import container image on server
      community.docker.docker_image:
        name: wh-starstone
        load_path: /tmp/wh-starstone-img.tar
        source: load
        state: present
      become: true

    - name: Ensure .env file exists
      ansible.builtin.template:
        src: env.j2
        dest: /home/chen/websites/wh-starstone/wh-starstone.env
        force: false  # do not recreate file if it already exists.
      vars:
        host: "{{ inventory_hostname }}"
        secret_key: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

    - name: Ensure db.sqlite3 file exists outside container
      ansible.builtin.file:
        path: /home/chen/websites/wh-starstone/db.sqlite3
        state: touch

    - name: Run container
      community.docker.docker_container:
        name: wh-starstone
        image: wh-starstone
        state: started
        recreate: true
        env_file: ~/websites/wh-starstone/wh-starstone.env
        mounts:
          - type: bind
            source: /home/chen/websites/wh-starstone/db.sqlite3
            target: /src/db.sqlite3
        ports: 81:8888

    - name: Run migration inside container
      community.docker.docker_container_exec:
        container: wh-starstone
        command: ./manage.py migrate