# Generated by Django 4.2.11 on 2024-06-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_item_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('text', 'list')},
        ),
    ]
